### ISSUE TITLE
Xtext validation pop up when using menu Unity VR on model

### ISSUE THREAD

**Issue by hqnghi88** [project-SIMPLE/gaml.extension.unity#11]
I am not sure if it is an real issue or just my setup go wrong. When using the plugin both by install url or  launch from eclipse, i have the popup error view of Xtext validation when i click on Finish button of wizard, the generated model are actually there.
<img width="435" alt="Screenshot 2024-02-07 at 16 05 04" src="https://github.com/project-SIMPLE/gaml.extension.unity/assets/6105384/3d1e4fe6-8e0e-4913-96f7-417ac184d97b">

Here is the log in eclipse console:

!ENTRY org.eclipse.core.jobs 4 2 2024-02-07 16:02:38.879
!MESSAGE An internal error occurred during: "Xtext validation".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.resources.IResource.exists()" because "this.resource" is null
	at org.eclipse.xtext.ui.editor.validation.AddMarkersOperation.execute(AddMarkersOperation.java:114)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.xtext.ui.editor.validation.MarkerIssueProcessor.processIssues(MarkerIssueProcessor.java:78)
	at msi.gama.lang.gaml.ui.editor.GamlEditor$3.run(GamlEditor.java:537)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.ui.workbench 4 0 2024-02-07 16:02:39.128
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.resources.IFile.getName()" because the return value of "org.eclipse.xtext.ui.editor.model.IXtextDocument.getAdapter(java.lang.Class)" is null
	at msi.gama.lang.gaml.ui.editor.GamlEditor.lambda$2(GamlEditor.java:642)
	at ummisco.gama.ui.utils.WorkbenchHelper$2.runInUIThread(WorkbenchHelper.java:409)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

**Comment by ptaillandier** [comment]
already fixed, see #4
